CHG: use --skip=<check> not --skip-<check>. Add --only=

diff --git a/builderrors b/builderrors
--- a/builderrors
+++ b/builderrors
@@ -2,99 +2,15 @@
 
 VERSION=1.1.3
 
-# Default options
-# NOTE: Bandit catches SQL injections only at low confidence. So default confidence to all, not medium/high
-BANDIT_CONFIDENCE=${BANDIT_CONFIDENCE:-all}     # Bandit reports only issues of given confidence level or higher
-BANDIT_SEVERITY=${BANDIT_SEVERITY:-all}         # Bandit reports only issues of given severity level or higher
-DUPLICATE_FILESIZE=${DUPLICATE_FILESIZE:-100}   # Max file size allowed for duplicate files
-DUPLICATE_LINES=${DUPLICATE_LINES:-50}          # Max # of duplicate lines allowed
-PY_LINE_LENGTH=${PY_LINE_LENGTH:-99}            # Python line length
-LFS_SIZE=${LFS_SIZE:-1000000}                   # Max file size you can commit without LFS
-RE_MINIFIED='[\.\-](min|pack)\.(js|css)$'       # RegEx for minified files
+# Foreground colors (ANSI escape codes)
+RED="\033[31;1m"
+GREEN="\033[32;1m"
+BROWN="\033[33;1m"
+YELLOW="\033[93;1m"
+CLEAR="\033[0m"
 
-# Set consistent sort order
-export LC_ALL=C
-
-# Refer https://stackoverflow.com/a/7948533/100904 for getopt usage
-OPTIONS=v
-LONGOPTS=verbose,skip-lib,skip-minified,skip-lfs,skip-prettier,skip-useless,skip-duplicate-files,skip-duplicate-lines,skip-py-filenames,skip-black,skip-flake8,skip-bandit,skip-eslint,skip-eslint-default,skip-stylelint,skip-htmlhint,skip-folders,skip-css-size,skip-code-size,skip-npm-audit,skip-flake8-extra,skip-pydoc,skip-absolute-urls,lfs-size:,duplicate-filesize:,duplicate-lines:,py-line-length:,bandit-confidence:,bandit-severity:
-TEMP=$(getopt --options "$OPTIONS" --longoptions "$LONGOPTS" --name builderrors -- "$@")
-if [ $? != 0 ] ; then echo "Could not run: builderrors $@" >&2 ; exit 1 ; fi
-eval set -- "$TEMP"
-while true; do
-  case "$1" in
-    "-v" | "--verbose" ) VERBOSE='--'; shift ;;
-    "--skip-lib" ) SKIP_LIB='--'; shift ;;
-    "--skip-minified" ) SKIP_MINIFIED='--'; shift ;;
-    "--skip-lfs" ) SKIP_LFS='--'; shift ;;
-    "--skip-prettier" ) SKIP_PRETTIER='--'; shift ;;
-    "--skip-useless" ) SKIP_USELESS='--'; shift ;;
-    "--skip-duplicate-files" ) SKIP_DUPLICATE_FILES='--'; shift ;;
-    "--skip-duplicate-lines" ) SKIP_DUPLICATE_LINES='--'; shift ;;
-    "--skip-py-filenames" ) SKIP_PY_FILENAMES='--'; shift ;;
-    "--skip-black" ) SKIP_BLACK='--'; shift ;;
-    "--skip-flake8" ) SKIP_FLAKE8='--'; shift ;;
-    "--skip-bandit" ) SKIP_BANDIT='--'; shift ;;
-    "--skip-eslint" ) SKIP_ESLINT='--'; shift ;;
-    "--skip-eslint-default" ) SKIP_ESLINT_DEFAULT='--'; shift ;;
-    "--skip-stylelint" ) SKIP_STYLELINT='--'; shift ;;
-    "--skip-htmlhint" ) SKIP_HTMLHINT='--'; shift ;;
-    "--skip-npm-audit" ) SKIP_NPM_AUDIT='--'; shift ;;
-    "--skip-flake8-extra" ) SKIP_FLAKE8_EXTRA='--'; shift ;;
-    "--skip-pydoc" ) SKIP_PYDOC='--'; shift ;;
-    "--skip-absolute-urls" ) SKIP_ABSOLUTE_URLS='--'; shift ;;
-    "--skip-folders" ) SKIP_FOLDERS='--'; shift ;;
-    "--skip-css-size" ) SKIP_CSS_SIZE='--'; shift ;;
-    "--skip-code-size" ) SKIP_CODE_SIZE='--'; shift ;;
-    "--lfs-size" ) LFS_SIZE=$2; shift 2 ;;
-    "--duplicate-filesize" ) DUPLICATE_FILESIZE=$2; shift 2 ;;
-    "--duplicate-lines" ) DUPLICATE_LINES=$2; shift 2 ;;
-    "--py-line-length" ) PY_LINE_LENGTH=$2; shift 2 ;;
-    "--bandit-severity" ) BANDIT_SEVERITY=$2; shift 2 ;;
-    "--bandit-confidence" ) BANDIT_CONFIDENCE=$2; shift 2 ;;
-    -- ) shift; break ;;
-    * ) break ;;
-  esac
-done
-
-# Run build error checks in $TARGET_DIR, which is set from environment variable, or command line, or .
-TARGET_DIR=${TARGET_DIR:-$1}
-TARGET_DIR=${TARGET_DIR:-.}
-
-if [[ -n "$VERBOSE" ]]; then
-  echo "builderrors   # version ${VERSION} \\"
-  echo "  ${VERBOSE:-# --}verbose \\"
-  echo "  ${SKIP_LIB:-# --}skip-lib \\"
-  echo "  ${SKIP_MINIFIED:-# --}skip-minified \\"
-  echo "  ${SKIP_LFS:-# --}skip-lfs \\"
-  echo "  ${SKIP_PRETTIER:-# --}skip-prettier \\"
-  echo "  ${SKIP_USELESS:-# --}skip-useless \\"
-  echo "  ${SKIP_DUPLICATE_FILES:-# --}skip-duplicate-files \\"
-  echo "  ${SKIP_DUPLICATE_LINES:-# --}skip-duplicate-lines \\"
-  echo "  ${SKIP_PY_FILENAMES:-# --}skip-py-filenames \\"
-  echo "  ${SKIP_BLACK:-# --}skip-black \\"
-  echo "  ${SKIP_FLAKE8:-# --}skip-flake8 \\"
-  echo "  ${SKIP_BANDIT:-# --}skip-bandit \\"
-  echo "  ${SKIP_ESLINT:-# --}skip-eslint \\"
-  echo "  ${SKIP_ESLINT_DEFAULT:-# --}skip-eslint-default \\"
-  echo "  ${SKIP_STYLELINT:-# --}skip-stylelint \\"
-  echo "  ${SKIP_HTMLHINT:-# --}skip-htmlhint \\"
-  echo "  ${SKIP_NPM_AUDIT:-# --}skip-npm-audit \\"
-  echo "  ${SKIP_FLAKE8_EXTRA:-# --}skip-flake8-extra \\"
-  echo "  ${SKIP_PYDOC:-# --}skip-pydoc \\"
-  echo "  ${SKIP_ABSOLUTE_URLS:-# --}skip-absolute-urls \\"
-  echo "  ${SKIP_FOLDERS:-# --}skip-folders \\"
-  echo "  ${SKIP_CSS_SIZE:-# --}skip-css-size \\"
-  echo "  ${SKIP_CODE_SIZE:-# --}skip-code-size \\"
-  echo "  --lfs-size=$LFS_SIZE \\"
-  echo "  --duplicate-filesize=$DUPLICATE_FILESIZE \\"
-  echo "  --duplicate-lines=$DUPLICATE_LINES \\"
-  echo "  --py-line-length=$PY_LINE_LENGTH \\"
-  echo "  --bandit-confidence=$BANDIT_CONFIDENCE \\"
-  echo "  --bandit-severity=$BANDIT_SEVERITY \\"
-  echo "  ${TARGET_DIR}"
-  echo ""
-fi
+# RegEx for minified files
+RE_MINIFIED='[\.\-](min|pack)\.(js|css)$'
 
 SCRIPT_DIR=`dirname "$(realpath "$0")"`
 NODE_DIR="$SCRIPT_DIR/node_modules/.bin"
@@ -106,15 +22,15 @@ if [ -x "$CYGPATH" ] ; then
   WIN_SCRIPT_DIR="$(cygpath -aw "$SCRIPT_DIR")"
 fi
 
-# By default, we don't have any errors
-EXIT_STATUS=0
+# Set consistent sort order
+export LC_ALL=C
 
-# Foreground colors (ANSI escape codes)
-RED="\033[31;1m"
-GREEN="\033[32;1m"
-BROWN="\033[33;1m"
-YELLOW="\033[93;1m"
-CLEAR="\033[0m"
+# Parse command-line options in Python. Strip \r in Windows
+eval $(python "$WIN_SCRIPT_DIR/parseoptions.py" "$@" | tr -d '\r')
+if [[ -z "$BUILDERROR_OPTIONS_PARSED" ]]; then exit 1 ; fi
+
+# To start with, we don't have any errors
+EXIT_STATUS=0
 
 # Usage: check $SKIP $TYPE $CODE $MSG $FIX
 #   $SKIP: Ignore check if specified
@@ -193,7 +109,7 @@ check-lfs() {
   #   #1: git files > 1 MB, sorted
   #   #2: git lfs files, sorted
   # Note: git ls-tree --format is supported only in Git 2.36+ (Apr 2022), so use --long instead
-  comm -23 <(git ls-tree -r --long HEAD | cut -c53- | awk -F'\t' "\$1 > $LFS_SIZE { print(\$2) }" | sort) <(git lfs ls-files -n | sort)
+  comm -23 <(git ls-tree -r --long HEAD | cut -c53- | awk -F'\t' "\$1 > ${LFS_SIZE:-1000000} { print(\$2) }" | sort) <(git lfs ls-files -n | sort)
 }
 check "$SKIP_LFS" "ERROR" "lfs" "use Git LFS for large files" ""
 
@@ -211,7 +127,7 @@ check-duplicate-files() {
   # Print as groups      - awk '...;sub(/^\*/, "", $2);...'
   #                      -          ^ strip leading * if Cygwin treats file as binary
   # Note: git ls-tree --format is supported only in Git 2.36+ (Apr 2022), so use --long instead
-  git ls-tree -r --long HEAD | cut -c53- | awk -F'\t' "\$1 > $DUPLICATE_FILESIZE { print(\$2) }" | tr '\n' '\0' | xargs -0 --no-run-if-empty md5sum | sort | uniq -w32 -dD | awk '{if(h!=$1){printf "\n"};sub(/^\*/, "", $2);for (i=2; i<=NF; ++i) printf "%s ", $i;printf "\n";h=$1}'
+  git ls-tree -r --long HEAD | cut -c53- | awk -F'\t' "\$1 > ${DUPLICATE_FILESIZE:-100} { print(\$2) }" | tr '\n' '\0' | xargs -0 --no-run-if-empty md5sum | sort | uniq -w32 -dD | awk '{if(h!=$1){printf "\n"};sub(/^\*/, "", $2);for (i=2; i<=NF; ++i) printf "%s ", $i;printf "\n";h=$1}'
 }
 check "$SKIP_DUPLICATE_FILES" "ERROR" "duplicate-files" "delete duplicate files" ""
 
@@ -220,7 +136,7 @@ check-duplicate-lines() {
   #   grep '^[a-zA-Z]'        # cut out the table
   #   grep -v '^Found '       # remove "Found <nn> clones"
   #   grep -v '^Detection '   # remove "Detection time: <nn>ms"
-  git ls-files | grep -E '\.(js|py|css|scss)$' | sort | tr '\n' '\0' | xargs -0 --no-run-if-empty "$NODE_DIR/jscpd" --min-lines="$DUPLICATE_LINES" 2>&1 | grep '^[a-zA-Z ]' | grep -v '^Found ' | grep -v '^Detection '
+  git ls-files | grep -E '\.(js|py|css|scss)$' | sort | tr '\n' '\0' | xargs -0 --no-run-if-empty "$NODE_DIR/jscpd" --min-lines="${DUPLICATE_LINES:-50}" 2>&1 | grep '^[a-zA-Z ]' | grep -v '^Found ' | grep -v '^Detection '
 }
 check "$SKIP_DUPLICATE_LINES" "ERROR" "duplicate-lines" "reduce duplicate lines" ""
 
@@ -229,13 +145,13 @@ check-prettier() {
   # NOTE: Don't run prettier on HTML files. It does not handle Tornado / Lodash templates
   git ls-files | grep -E '\.(js|jsx|vue|ts|css|scss|sass|yaml|md)$' | grep -v -E "$RE_MINIFIED" | sort | tr '\n' '\0' | xargs -0 --no-run-if-empty "$NODE_DIR/prettier" --loglevel=warn --check 2>&1
 }
-check "$SKIP_PRETTIER" "ERROR" "prettier" "auto-format JS/CSS with Prettier" "npx prettier --write \"**/*.{js,jsx,vue,ts,css,scss,sass,yaml,md}\"" \
+check "$SKIP_PRETTIER" "ERROR" "prettier" "auto-format JS/CSS with Prettier" "npx prettier --write \"**/*.{js,jsx,vue,ts,css,scss,sass,yaml,md}\""
 
 check-black() {
   # black prints "All done!" and "Oh no!" and "<nn> files would be left unchanged." with unicode characters and color. Strip these with "grep -v ..."
-  git ls-files | grep -E '\.py$' | sort | tr '\n' '\0' | xargs -0 --no-run-if-empty black --check --skip-string-normalization --line-length=${PY_LINE_LENGTH} 2>&1 | grep -v "^All done!" | grep -v "^Oh no!" | grep -v "would be left unchanged."
+  git ls-files | grep -E '\.py$' | sort | tr '\n' '\0' | xargs -0 --no-run-if-empty black --check --skip-string-normalization --line-length=${PY_LINE_LENGTH:-99} 2>&1 | grep -v "^All done!" | grep -v "^Oh no!" | grep -v "would be left unchanged."
 }
-check "$SKIP_BLACK" "ERROR" "black" "auto-format Python with Black" "black . --skip-string-normalization --line-length=99" \
+check "$SKIP_BLACK" "ERROR" "black" "auto-format Python with Black" "black . --skip-string-normalization --line-length=${PY_LINE_LENGTH:-99}"
 
 check-py-filenames() {
   git ls-files | grep '\.py$' | sort | grep -e '[^a-z0-9_./]'
@@ -252,7 +168,7 @@ check-flake8() {
 check "$SKIP_FLAKE8" "ERROR" "flake8" "fix Python errors" ""
 
 check-bandit() {
-  git ls-files | grep '\.py$' | sort | tr '\n' '\0' | xargs -0 --no-run-if-empty bandit --format txt --severity-level $BANDIT_SEVERITY --confidence-level $BANDIT_CONFIDENCE --quiet 2>/dev/null
+  git ls-files | grep '\.py$' | sort | tr '\n' '\0' | xargs -0 --no-run-if-empty bandit --format txt --severity-level ${BANDIT_SEVERITY:-all} --confidence-level ${BANDIT_CONFIDENCE:-all} --quiet 2>/dev/null
 }
 check "$SKIP_BANDIT" "ERROR" "bandit" "fix Python security errors" ""
 
@@ -300,7 +216,7 @@ if [[ -z "$SKIP_HTMLHINT" ]]; then
     cp "$SCRIPT_DIR/.htmlhintrc" .
     CREATED_HTMLHINTRC=1
   fi
-  check "$SKPI_HTMLHINT" "ERROR" "htmlhint" "fix HTML errors" ""
+  check "$SKIP_HTMLHINT" "ERROR" "htmlhint" "fix HTML errors" ""
   if [[ -n "$CREATED_HTMLHINTRC" ]]; then
     rm .htmlhintrc
   fi
